import {load} from 'cheerio';
import {XMLParser} from 'fast-xml-parser';
import {sources,type Source} from './sources.ts';
import type {Item,Feed} from './types.ts';
const TTL=15*60*1000;
const memory=new Map<string,Feed>();
const pending=new Map<string,Promise<Feed>>();
export function safeUrl(raw:unknown,base:string){try{if(typeof raw!=='string'||!raw.trim()||raw.startsWith('#'))return '';const u=new URL(raw,base);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)return '';for(const key of [...u.searchParams.keys()])if(key.startsWith('utm_')||['fbclid','gclid'].includes(key))u.searchParams.delete(key);return u.href;}catch{return '';}}
export function plain(raw:unknown){return load(typeof raw==='string'?raw:String(raw??'')).text().replace(/\s+/g,' ').trim();}
const date=(v:unknown)=>{if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const d=Date.parse(String(v??''));return Number.isFinite(d)?new Date(d).toISOString():undefined;};
async function request(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(14000),headers:{'User-Agent':'AI-Radar/1.0 (+public-feed-reader)','Accept':'application/rss+xml, application/atom+xml, application/json, text/html;q=0.9'}});if(!r.ok)throw new Error('HTTP '+r.status);const reader=r.body?.getReader();if(!reader)throw Error('empty response');let size=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>3_500_000){await reader.cancel();throw Error('response too large')}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}return new TextDecoder().decode(bytes);}
export async function collect(s:Source):Promise<Item[]>{
 const out:Item[]=[];
 function add(v:Partial<Item>&{title:string;url:string}){const url=safeUrl(v.url,s.url);const title=plain(v.title).slice(0,240);if(!url||title.length<2||out.some(i=>i.url===url&&i.kind===(v.kind||'recommended')))return;out.push({...v,title,url,source:s.id,rank:v.rank??out.length+1,kind:v.kind||'recommended',summary:v.summary?plain(v.summary).slice(0,450):undefined,publishedAt:date(v.publishedAt)});}
 const body=await request(s.feed||s.url);
 if(s.adapter==='aihot'){const json=JSON.parse(body);if(!Array.isArray(json.items))throw Error('format changed');for(const i of json.items.slice(0,25))add({title:i.title,url:i.links?.original||i.links?.aihot,via:safeUrl(i.links?.aihot,s.url),summary:i.summary,publishedAt:i.publishedAt,reason:plain(i.reason).slice(0,250),metric:typeof i.score==='number'?`原站推荐评分 ${i.score} · 非热度`:undefined});}
 else if(s.adapter==='rss'){const p=new XMLParser({ignoreAttributes:false,processEntities:false});const json=p.parse(body);const channel=json.rss?.channel;const entries=channel?.item||json.feed?.entry||[];for(const i of (Array.isArray(entries)?entries:[entries]).slice(0,25)){let link=i.link;if(Array.isArray(link))link=link.find(l=>l['@_rel']==='alternate')||link[0];if(typeof link==='object')link=link['@_href']||link['#text'];add({title:typeof i.title==='object'?i.title['#text']:i.title,url:link||i.guid?.['#text']||i.guid,summary:typeof i.description==='string'?i.description:typeof i.summary==='string'?i.summary:i.summary?.['#text']||i.content?.['#text'],publishedAt:i.pubDate||i.published||i.updated});}}
 else if(s.adapter==='hn'){const $=load(body);$('.athing').each((_,el)=>{const row=$(el),link=row.find('.titleline>a').first(),title=link.text();if(!/\b(ai|llm|gpt|claude|gemini|deepseek|agent|openai|anthropic|model|neural|machine learning)\b/i.test(title))return;const meta=row.next();add({title,url:link.attr('href')||'',kind:'hot',rank:Number(row.find('.rank').text().replace('.',''))||out.length+1,metric:meta.find('.score').text()+' · 原站榜单 #'+row.find('.rank').text().replace('.',''),publishedAt:meta.find('.age').attr('title')?.split(' ')[0],via:'https://news.ycombinator.com/item?id='+row.attr('id')});});}
 else if(s.adapter==='hf'){const j=JSON.parse(body);for(const i of (Array.isArray(j)?j:[]).sort((a,b)=>(b.paper?.upvotes||0)-(a.paper?.upvotes||0)).slice(0,25))add({title:i.title||i.paper?.title,url:'https://huggingface.co/papers/'+i.paper?.id,kind:'hot',summary:i.summary||i.paper?.summary,publishedAt:i.publishedAt||i.paper?.publishedAt,metric:`${i.paper?.upvotes||0} 票 · 原站票数`});}
 else {const $=load(body);
  if(s.adapter==='guizang'){$('script').each((_,el)=>{const text=$(el).text();const match=text.match(/self\.__next_f\.push\((\[[\s\S]*\])\)/);if(!match)return;try{const payload=JSON.parse(match[1]);if(typeof payload[1]!=='string')return;for(const m of payload[1].matchAll(/\{"slug":"[^\n]+?"date":"\d{4}-\d{2}-\d{2}"\}/g)){try{const i=JSON.parse(m[0]);if(i.title&&i.url)add({title:i.title,url:i.url,summary:i.description,publishedAt:i.date,via:s.url});}catch{}}}catch{}});}
  $('script,style,nav,header,footer,.logo').remove();
  if(s.id==='xiaohu'){$('a.latest-card,a.archive-card').each((_,el)=>{const a=$(el);add({title:a.find('.latest-headline,.archive-headline').first().text(),url:a.attr('href')||'',summary:a.find('.latest-summary').text(),publishedAt:a.attr('href')?.match(/20\d\d-\d\d-\d\d/)?.[0]});});return out.slice(0,30);}
  if(s.adapter==='uisdc'){$('.p-item-wrap').each((_,el)=>{const e=$(el);const title=e.find('.p-item-title').text();if(title)add({title,url:e.attr('href')||'',kind:'recommended',metric:'原站今日情报工具 #'+(e.find('.p-item-num').text()||out.length+1)});});}
  $('h2,h3,h4').each((_,el)=>{const h=$(el);let a=h.closest('a');if(!a.length)a=h.find('a').first();if(!a.length)a=h.closest('article').find('a[href]').first();if(!a.length&&s.adapter==='guizang')a=h.parent().parent().find('a').first();if(!a.length)return;const title=plain(h.text()).replace(/^(精选|New(?=[\u4e00-\u9fff]))/,'');const url=a.attr('href')||'';if(title.length<9||/^(菜单|关于|今日AI情报观察|最新AI工具|行业新闻|知识9图|每日打卡|热门文章|View all|Subscribe|Latest News|Latest Updates|Read more)/i.test(title))return;if(s.adapter==='uisdc'&&(a.hasClass('p-item-wrap')||a.closest('.widget-news-industry').length))return;const block=h.closest('article').length?h.closest('article'):h.parent();const text=block.text();add({title,url,summary:block.find('p').first().text(),publishedAt:block.find('time').attr('datetime')||url.match(/20\d\d[-/]\d{1,2}[-/]\d{1,2}/)?.[0]||text.match(/20\d\d[-/]\d{1,2}[-/]\d{1,2}/)?.[0]});});
  if(['daily','smol'].includes(s.adapter||'')){$('a[href]').each((_,el)=>{const a=$(el),href=a.attr('href')||'',title=plain(a.find('h2,h3').first().text()||a.text()).replace(/ Show details$/,'');if(title.length<12||!/\/(?:posts?|issues?|daily|news|zh|20\d\d|en)[/\-?]|20\d\d-\d\d-\d\d/.test(href))return;if(/^(view all|see all|查看更多|历史归档)/i.test(title))return;add({title,url:href,publishedAt:href.match(/20\d\d-\d\d-\d\d/)?.[0]||(s.adapter==='smol'&&href.match(/issues\/(\d{2}-\d{2}-\d{2})/)?.[1]?'20'+href.match(/issues\/(\d{2}-\d{2}-\d{2})/)![1]:undefined)});});}
 }
 return out.slice(0,30);
}
export async function getFeed(id:string):Promise<Feed>{const s=sources.find(s=>s.id===id);if(!s?.adapter)throw Error('unknown source');let cached=memory.get(id);if(cached&&Date.now()-Date.parse(cached.fetchedAt)<(cached.status==='error'?60000:TTL))return cached;if(pending.has(id))return pending.get(id)!;
 const job=(async()=>{try {const items=await collect(s);if(!items.length)throw Error('no readable items');const f:Feed={source:id,items,status:'ok',fetchedAt:new Date().toISOString()};memory.set(id,f);return f;}catch{if(cached?.items.length)return {...cached,status:'stale' as const,message:'本次读取失败，显示上次成功内容'};const f:Feed={source:id,items:[],status:'error',message:'原站暂不可读或页面已变化，可直接访问原站',fetchedAt:new Date().toISOString()};memory.set(id,f);return f;}finally{pending.delete(id)}})();pending.set(id,job);return job;
}
