export type Source={id:string;name:string;url:string;group:string;lang:string;description:string;short:string;color:string;label:string;hotLabel?:string;adapter?:string;feed?:string;default?:boolean};
const records = [
 ['aihot','AIHOT','https://aihot.news','独立资讯','中文','卡兹克的 AI 热点精选','HOT','#ed713f','原站精选','aihot','https://aihot.news/api/v1/items',true],
 ['tldr','AI/TLDR','https://ai-tldr.dev/','独立资讯','英文','模型、工具、论文与开源发布','TL','#7661d6','发布精选','rss','https://ai-tldr.dev/feed.xml',true],
 ['guizang','歸藏的 AI 资讯','https://www.guizang.ai/','独立资讯','中文','AI 动态、创作与工作流','藏','#303e5b','原站动态','guizang','',true],
 ['uisdc','优设 AI 情报','https://www.uisdc.com/news','独立资讯','中文','设计师与 AI 创作者情报','优','#ee8c35','情报推荐','uisdc','',true],
 ['airebao','AI 热报','https://airebao.com/','独立资讯','中文','精选 AI 资讯与多来源线索','报','#d96a62','原站精选','headings','',true],
 ['smol','AINews · smol.ai','https://news.smol.ai/','社区研究','英文','Discord、Reddit、X 社区讨论摘要','S','#69834e','社区摘要','smol','',true],
 ['xiaohu','小互 AI 日报','https://daily.xiaohu.ai/','独立资讯','中文','按日期回看的 AI 动态精选','互','#4a9ca4','日报精选','daily','',true],
 ['yage-daily','鸭哥每日 AI 要闻','https://daily.yage.ai/','独立资讯','中文','每日资讯、观点与证据线索','鸭','#dd9b35','每日要闻','rss','https://daily.yage.ai/index.xml',true],
 ['dailydawn','DailyDawn','https://dailydawn.dev/','独立资讯','双语','独立开发者的趋势日报','D','#597fe2','趋势日报','daily','',true],
 ['radar','AI·RADAR','https://radar.suversal.com/latest','独立资讯','中文','精选与日报、周报、月报','R','#3ba688','原站精选','headings','',true],
 ['baoyu','宝玉的分享','https://baoyu.io/','作者博客','中文','原创、翻译与 AI 编程实践','玉','#5271ce','作者更新','headings','',true],
 ['hn','Hacker News · AI','https://news.ycombinator.com/','社区研究','英文','开发者社区 AI 相关热门讨论','Y','#f08036','热门讨论','hn','',true],
 ['ainewslog','AI News Log','https://www.ainewslog.com/zh/','独立资讯','中文','资讯、研究与开源项目日历','N','#6284b9','每日精选','daily'],
 ['zgba','AI 日报 · ZGBA','https://daily.zgba.com/','独立资讯','中文','研究博客与媒体内容汇总','Z','#638978','每日精选','daily'],
 ['uraitools','AI 资讯日报','https://news.uraitools.com/','独立资讯','中文','产品更新与研究资讯归档','U','#826ec0','每日精选','daily'],
 ['aitnt','AITNT','https://www.aitntnews.com/ainews/zh-CN','独立资讯','中文','全球 AI 新闻日报','T','#5976bb','新闻日报','headings'],
 ['orbit','Orbit Daily','https://www.orbitdailyai.com/','独立资讯','英文','新闻、论文与开源项目','O','#7c77b0','首页推荐'],
 ['zhao','zhaosite','https://www.zhaosite.com/news','独立资讯','中文','分类聚合国内外 AI 资讯','Z','#839164','资讯聚合'],
 ['jiazhuang','加装 AI 助手','https://jiazhuangai.com/','独立资讯','中文','工具实践与模型动态','加','#7c96a0','首页推荐'],
 ['yage','Computing Life','https://yage.ai/','作者博客','双语','鸭哥的 AI 实验和工程笔记','Y','#aa8d5e','作者更新','headings'],
 ['simon','Simon Willison','https://simonwillison.net/','作者博客','英文','LLM 实验、开发与技术评论','SW','#5e8293','作者更新','rss','https://simonwillison.net/atom/everything/'],
 ['latent','Latent Space','https://www.latent.space/','作者博客','英文','AI 工程、访谈与播客','LS','#6d71b7','作者更新','rss','https://www.latent.space/feed'],
 ['interconnects','Interconnects','https://www.interconnects.ai/','作者博客','英文','开放模型与后训练分析','IC','#e28b49','作者更新','rss','https://www.interconnects.ai/feed'],
 ['ahead','Ahead of AI','https://magazine.sebastianraschka.com/','作者博客','英文','Sebastian Raschka 的研究通讯','A','#598a72','作者更新','rss','https://magazine.sebastianraschka.com/feed'],
 ['import','Import AI','https://importai.substack.com/','作者博客','英文','Jack Clark 的研究与影响分析','IA','#8a749d','作者更新','rss','https://importai.substack.com/feed'],
 ['useful','One Useful Thing','https://www.oneusefulthing.org/','作者博客','英文','Ethan Mollick 的工作与教育观察','1','#c1885e','作者更新','rss','https://www.oneusefulthing.org/feed'],
 ['normal','AI as Normal Technology','https://www.normaltech.ai/','作者博客','英文','AI 评估与社会影响评论','NT','#778fa7','作者更新','rss','https://www.normaltech.ai/feed'],
 ['supremacy','AI Supremacy','https://www.ai-supremacy.com/','作者博客','英文','产业与趋势通讯','AS','#568e9c','作者更新','rss','https://www.ai-supremacy.com/feed'],
 ['lilian','Lil’Log','https://lilianweng.github.io/','作者博客','英文','Lilian Weng 的研究笔记','L','#88906b','研究笔记','rss','https://lilianweng.github.io/index.xml'],
 ['chip','Chip Huyen','https://huyenchip.com/blog/','作者博客','英文','AI 工程、系统与评估','CH','#aa7c8e','作者更新','rss','https://huyenchip.com/feed.xml'],
 ['tldrtech','TLDR AI','https://tldr.tech/ai','独立资讯','英文','新闻、研究与产品简报','TL','#6c7796','每日简报'],
 ['lastweek','Last Week in AI','https://lastweekin.ai/','独立资讯','英文','每周回顾与播客','LW','#758960','周度回顾','rss','https://lastweekin.ai/feed'],
 ['futuretools','Future Tools','https://futuretools.io/news','独立资讯','英文','新工具与创作者产品新闻','FT','#9569c5','工具资讯','headings'],
 ['neuron','The Neuron','https://www.theneurondaily.com/','独立资讯','英文','AI 新闻与实用内容','N','#55a097','每日推荐','headings'],
 ['report','The AI Report','https://www.theaireport.ai/','独立资讯','英文','面向商业应用的 AI 通讯','AR','#707dd0','应用简报','headings'],
 ['decoder','THE DECODER','https://the-decoder.com/','科技媒体','英文','AI 新闻、商业与研究','DE','#b56d65','新闻推荐','rss','https://the-decoder.com/feed/'],
 ['marktech','MarkTechPost','https://www.marktechpost.com/','科技媒体','英文','模型、开源与 Agent 新闻','M','#66a599','新闻推荐','rss','https://www.marktechpost.com/feed/'],
 ['aibot','AI 工具集','https://ai-bot.cn/daily-ai-news/','独立资讯','中文','新闻、工具与产品动态','AI','#6a7dda','每日资讯','headings'],
 ['aigc','AIGC 工具导航','https://www.aigc.cn/news','独立资讯','中文','生成式 AI 行业资讯','AG','#4e9b9a','新闻推荐','headings'],
 ['gaojun','高军 AI 日报','https://github.com/Freelander/AI-Daily','独立资讯','中文','工具、绘画、开源与教程','高','#6a8f6b','公开归档'],
 ['oraink','灵砚 Oraink','https://github.com/Oraink-News/tech-digest','独立资讯','中文','科技日报与周报公开归档','砚','#8598a6','公开归档'],
 ['miutu','缪兔 AI 信息差','https://github.com/Zehebi29/daily-ai-news','独立资讯','中文','AI 工具与事件清单','兔','#9c77a2','公开归档'],
 ['newslist','AI Newsletter 目录','https://github.com/aitools-coffee/Open-Source-AI-News','独立资讯','英文','继续发现更多独立通讯','NL','#697ba4','来源目录'],
 ['hypedelta','HypeDelta 来源目录','https://github.com/rickoslyder/HypeDelta/blob/main/canonical_ai_research_sources.md','社区研究','英文','研究博客与通讯目录','HD','#7a8e77','来源目录'],
 ['jiqizhixin','机器之心','https://www.jiqizhixin.com/industry','科技媒体','中文','研究、模型与产业报道','机','#426693','产业资讯','headings'],
 ['qbit','量子位','https://www.qbitai.com/','科技媒体','中文','AI 新产品与前沿科技','量','#387ade','新闻推荐','rss','https://www.qbitai.com/feed'],
 ['zhidx','智东西','https://www.zhidx.com/','科技媒体','中文','产业、芯片与智能硬件','智','#437799','新闻推荐','headings'],
 ['leiphone','雷峰网','https://www.leiphone.com/','科技媒体','中文','人物、企业与产业报道','雷','#67918a','新闻推荐','headings'],
 ['aibase','AIbase','https://www.aibase.com/zh','独立资讯','中文','AI 快讯、工具与热点','AB','#7668c3','资讯推荐','headings'],
 ['techcrunch','TechCrunch AI','https://techcrunch.com/category/artificial-intelligence/','科技媒体','英文','AI 公司与新产品','TC','#3a9966','AI 新闻','rss','https://techcrunch.com/category/artificial-intelligence/feed/'],
 ['verge','The Verge AI','https://www.theverge.com/ai-artificial-intelligence','科技媒体','英文','产品、平台与行业争议','V','#7650c6','AI 新闻'],
 ['venture','VentureBeat AI','https://venturebeat.com/ai','科技媒体','英文','企业 AI 应用','VB','#a56c76','AI 新闻'],
 ['wired','WIRED AI','https://www.wired.com/tag/artificial-intelligence/','科技媒体','英文','AI 社会与文化议题','W','#41506b','AI 新闻'],
 ['rundown','The Rundown AI','https://www.therundown.ai/','独立资讯','英文','每日摘要与应用案例','RD','#426e89','每日推荐','headings'],
 ['hf','Hugging Face Papers','https://huggingface.co/papers/trending','社区研究','英文','研究社区热门论文','HF','#bf963a','热门论文','hf','https://huggingface.co/api/daily_papers'],
 ['github','GitHub Trending','https://github.com/trending','社区研究','英文','热门开源项目，需筛选 AI','GH','#526079','开源榜单'],
 ['reddit','Reddit · LocalLLaMA','https://www.reddit.com/r/LocalLLaMA/','社区研究','英文','开放模型与本地部署讨论','R','#d87545','社区热榜'],
 ['v2ex','V2EX','https://www.v2ex.com/','社区研究','中文','开发者工具使用反馈','V2','#5d889d','社区讨论'],
 ['infoq','InfoQ 中文','https://www.infoq.cn/AI','科技媒体','中文','企业应用与技术实践','IQ','#7460a7','AI 资讯'],
 ['huxiu','虎嗅','https://www.huxiu.com/so/1370.html','科技媒体','中文','商业观点与行业争议','虎','#69876e','商业观点'],
 ['cls','财联社 AI','https://www.cls.cn/subject/1321','科技媒体','中文','产业与企业动态','财','#5681a0','行业资讯'],
 ['jiemian','界面新闻 AI','https://www.jiemian.com/tags/3066/1.html','科技媒体','中文','商业化与社会议题','界','#627e97','行业资讯'],
 ['36kr','36氪','https://36kr.com/','科技媒体','中文','创业、融资与商业化','氪','#628de0','商业资讯'],
 ['ithome','IT之家','https://www.ithome.com/','科技媒体','中文','产品更新与科技快讯','IT','#ce6767','科技快讯'],
 ['geekpark','极客公园','https://www.geekpark.net/','科技媒体','中文','产品与创业者观察','极','#a48157','科技资讯'],
 ['zhihu','知乎','https://www.zhihu.com/','社区研究','中文','长回答与观点讨论','知','#497fd2','社区讨论'],
 ['weibo','微博热搜','https://s.weibo.com/top/summary','社区研究','中文','大众传播与突发话题','微','#d78850','热搜'],
 ['bilibili','哔哩哔哩','https://www.bilibili.com/','社区研究','中文','视频测评与创作讨论','B','#6ca8c2','视频社区'],
 ['batch','The Batch','https://www.deeplearning.ai/the-batch/','社区研究','英文','AI 周报与研究解读','B','#6584bc','每周精选'],
 ['mit','MIT Technology Review','https://www.technologyreview.com/topic/artificial-intelligence/','科技媒体','英文','AI 技术与社会影响','MIT','#59677d','AI 资讯'],
 ['producthunt','Product Hunt','https://www.producthunt.com/','社区研究','英文','新产品与早期用户反馈','PH','#d37c58','产品榜单']
] as const;
export const sources:Source[]=records.map(r=>({id:r[0],name:r[1],url:r[2],group:r[3],lang:r[4],description:r[5],short:r[6],color:r[7],label:r[8],adapter:r[9],feed:r[10]||undefined,default:(!!r[11]&&!['airebao','yage-daily'].includes(r[0]))||r[0]==='hf',hotLabel:r[0]==='hn'?'社区热门 · AI 筛选':r[0]==='hf'?'每日论文 · 原站票数':undefined}));
